
name: cd
on:
  push:
    tags:
    - "v[0-9]+.[0-9]"
jobs:
  build-release:
    name: build-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/nxcloudnotes
            asset_name: nxcloudnotes-linux
          - name: macos
            os: macos-latest
            artifact_name: target/release/nxcloudnotes
            asset_name: nxcloudnotes-macos

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install packages (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends openssl
    - name: Install packages (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install openssl@1.1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Build
      run: cargo build --release --locked

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}